---

- name: Create group
  ansible.builtin.group:
    name: "{{ vault_group }}"

- name: Create user
  ansible.builtin.user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    groups: certs
    append: true
    system: yes
    shell: "/sbin/nologin"
    create_home: "no"
    state: present

- name: Install prerequisites
  ansible.builtin.package:
    name: "{{ vault_install_prerequisites }}"
    update_cache: yes

- name: Set Vault architecture fact
  ansible.builtin.set_fact:
    vault_arch: "{{ arch_map[ansible_architecture] | default(ansible_architecture) }}"
  vars:
    arch_map:
      x86_64: "amd64"
      aarch64: "arm64"
      armv7l: "arm"
      i386: "386"

- name: Download and unzip archive
  ansible.builtin.unarchive:
    src: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_{{ vault_arch }}.zip"
    dest: /usr/local/bin
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0755
    remote_src: yes

- name: Set vault binary capabilities
  community.general.capabilities:
    path: /usr/local/bin/vault
    capability: cap_ipc_lock+ep
    state: present

- name: Create service file
  ansible.builtin.template:
    src: init.service.j2
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root
  notify: systemd_reload

- name: Create config file
  ansible.builtin.template:
    src: vault.hcl.j2
    dest: "{{ vault_config_path }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"

- name: Enable and start service
  ansible.builtin.service:
    name: vault
    state: started
    enabled: yes
