---

- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install unzip
      ansible.builtin.package:
        name: unzip
        state: present

    - name: Unarchive AWS CLI bundle
      ansible.builtin.unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /
        remote_src: yes

    - name: Install the AWS CLI
      shell: /aws/install

    - name: Generate an SSH which will be used to connect to the EC2 instance
      community.crypto.openssh_keypair:
        path: ~/id_rsa

- hosts: all
  remote_user: ec2-user
  vars:
    ansible_ssh_private_key_file: ~/id_rsa
  gather_facts: no
  pre_tasks:
    - name: Tell EC2 Instance Connect about our SSH key
      ansible.builtin.shell: >-
        aws ec2-instance-connect send-ssh-public-key
        --region {{ placement.region }}
        --availability-zone {{ placement.availability_zone }}
        --instance-id {{ instance_id }}
        --instance-os-user ec2-user
        --ssh-public-key file://~/id_rsa.pub
      delegate_to: 127.0.0.1

    - name: Get summary information about the CloudFormation stack
      amazon.aws.cloudformation_info:
        stack_name: InfrastructureVaultStack
      register: cfn_output
      delegate_to: 127.0.0.1

    - name: Set DynamoDB table name as fact
      ansible.builtin.set_fact:
        vault_storage_dynamodb_table_name: "{{ cfn_output.cloudformation.InfrastructureVaultStack.stack_outputs.VaultStorageTableName }}"

  roles:
    - name: vault
      become: yes
