---

- hosts: all
  tasks:
    - name: Gather EC2 metadata facts
      amazon.aws.ec2_metadata_facts:

    - name: Setup Ansible environment by installing roles
      ansible.builtin.include_tasks:
        file: setup.yml

    - name: Install and configure HashiCorp Vault
      ansible.builtin.include_tasks:
        file: vault.yml
