---

- name: Install collections and roles from Galaxy
  community.general.ansible_galaxy_install:
    type: both
    requirements_file: requirements.yml
    force: true

- name: Install required Python modules
  ansible.builtin.package:
    name:
      # Required by amazon.aws.secretsmanager_secret lookup
      - python3-boto3
      # Required by ansible.builtin.dnf module
      - python3-dnf
    state: present
