---

- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Ensure Nginx is started and enabled
  ansible.builtin.systemd_service:
    name: nginx
    state: started
    enabled: true

- name: Pass variables to role
  ansible.builtin.include_role:
    name: acme
  vars:
    acme_cert_domain: vault.dylanw.net
    acme_contact: admin@dylanw.net
    cloudflare_zone: dylanw.net

- name: Pass variables to role
  ansible.builtin.include_role:
    name: nginxinc.nginx_config
  vars:
    nginx_config_http_template_enable: true
    nginx_config_http_template:
      - deployment_location: /etc/nginx/conf.d/vault.conf
        config:
          servers:
            - core:
                listen:
                  - port: 443
                    address: '[::]'
                    ssl: yes
                  - port: 443
                    ssl: yes
                server_name:
                  - vault.dylanw.net
              ssl:
                certificate: "/etc/acme/certs/vault.dylanw.net/fullchain.pem"
                certificate_key: "/etc/acme/keys/vault.dylanw.net.pem"
                prefer_server_ciphers: yes
                session_timeout: 1d
                session_cache:
                  shared:
                    name: SSL
                    size: 50m
                session_tickets: no
              locations:
                - location: /
                  proxy:
                    pass: http://127.0.0.1:8200
                    set_header:
                      - field: Host
                        value: '$host'
                      - field: X-Real-IP
                        value: '$remote_addr'
                      - field: X-Forwarded-For
                        value: '$proxy_add_x_forwarded_for'
                      - field: X-Forwarded-Proto
                        value: https

- name: Pass variables to role
  ansible.builtin.include_role:
   name: vault

- name: Get public IP address
  ansible.builtin.uri:
    url: http://checkip.amazonaws.com/
    return_content: true
  register: public_ip_address

- name: Create A record for on CloudFlare DNS
  community.general.cloudflare_dns:
    zone: dylanw.net
    record: vault
    type: A
    value: "{{ public_ip_address }}"
    api_token: "{{ lookup('amazon.aws.aws_secret', cloudflare_token_secret_name, region=current_region) }}"
  delegate_to: 127.0.0.1
